export const storagePath = ''
export const defaultConfigPath = storagePath + '/default'
export const pluginPath = defaultConfigPath + '/plugins'
export const pluginConfigName = 'config.json'
export const pluginFileName = 'index.js'
